/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

/**
 *
 * @author luzme
 */
public class Moservicios extends javax.swing.JFrame {

    /**
     * Creates new form moservicios
     */
    public Moservicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        moidser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mofecha = new javax.swing.JTextField();
        monombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        moservicio = new javax.swing.JTextField();
        moguardar = new javax.swing.JButton();
        mocancelar = new javax.swing.JButton();
        eliminarser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 2, 18)); // NOI18N
        jLabel3.setText("Id del Servicio:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, -1));
        getContentPane().add(moidser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, 30));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 2, 18)); // NOI18N
        jLabel2.setText("Nueva Fecha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 140, -1));
        getContentPane().add(mofecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 130, 30));
        getContentPane().add(monombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 180, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 2, 18)); // NOI18N
        jLabel4.setText("Nuevo Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 2, 18)); // NOI18N
        jLabel5.setText("Nuevo Servicio:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, -1));
        getContentPane().add(moservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 310, 70));

        moguardar.setFont(new java.awt.Font("Yu Gothic Medium", 2, 14)); // NOI18N
        moguardar.setText("Guardar");
        getContentPane().add(moguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        mocancelar.setFont(new java.awt.Font("Yu Gothic Medium", 2, 14)); // NOI18N
        mocancelar.setText("Cancelar");
        mocancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mocancelarMouseClicked(evt);
            }
        });
        getContentPane().add(mocancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        eliminarser.setFont(new java.awt.Font("Yu Gothic Medium", 2, 14)); // NOI18N
        eliminarser.setText("Eliminar Servicio");
        getContentPane().add(eliminarser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 510, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mocancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mocancelarMouseClicked
presentacion.Servicio servicio= new presentacion.Servicio();
    servicio.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_mocancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Moservicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Moservicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Moservicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Moservicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Moservicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminarser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton mocancelar;
    private javax.swing.JTextField mofecha;
    private javax.swing.JButton moguardar;
    private javax.swing.JTextField moidser;
    private javax.swing.JTextField monombre;
    private javax.swing.JTextField moservicio;
    // End of variables declaration//GEN-END:variables
}
