/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

/**
 *
 * @author luzme
 */
public class Mousuario extends javax.swing.JFrame {

    /**
     * Creates new form moencargado
     */
    public Mousuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        newidusu = new javax.swing.JTextField();
        newnameusu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newphoneusu = new javax.swing.JTextField();
        newpasswusu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        guardarcam = new javax.swing.JButton();
        cancelcam = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 2, 18)); // NOI18N
        jLabel2.setText("Id del Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 140, -1));
        jPanel1.add(newidusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 180, 30));
        jPanel1.add(newnameusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 200, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 2, 18)); // NOI18N
        jLabel3.setText("Nuevo Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 140, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 2, 18)); // NOI18N
        jLabel4.setText("Nuevo Número telefónico:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 220, -1));
        jPanel1.add(newphoneusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 180, 30));
        jPanel1.add(newpasswusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 200, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 2, 18)); // NOI18N
        jLabel5.setText("Nueva Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 180, -1));

        guardarcam.setFont(new java.awt.Font("Yu Gothic Medium", 2, 14)); // NOI18N
        guardarcam.setText("Guardar");
        jPanel1.add(guardarcam, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        cancelcam.setFont(new java.awt.Font("Yu Gothic Medium", 2, 14)); // NOI18N
        cancelcam.setText("Cancelar");
        cancelcam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelcamMouseClicked(evt);
            }
        });
        jPanel1.add(cancelcam, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/13.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 510, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelcamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelcamMouseClicked
presentacion.Usuario usuario= new presentacion.Usuario();
    usuario.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cancelcamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mousuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mousuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mousuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mousuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mousuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelcam;
    private javax.swing.JButton guardarcam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newidusu;
    private javax.swing.JTextField newnameusu;
    private javax.swing.JTextField newpasswusu;
    private javax.swing.JTextField newphoneusu;
    // End of variables declaration//GEN-END:variables
}
