/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

/**
 *
 * @author luzme
 */
public class Usuario extends javax.swing.JFrame {

    /**
     * Creates new form añencargado
     */
    public Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cancelañadir = new javax.swing.JButton();
        agregarusu = new javax.swing.JButton();
        nameusu = new javax.swing.JTextField();
        passwusuario = new javax.swing.JPasswordField();
        btnconusuario = new javax.swing.JButton();
        btnmodusuario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        idusuario1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 2, 18)); // NOI18N
        jLabel2.setText("Nombre del Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 180, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 2, 18)); // NOI18N
        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 110, -1));

        cancelañadir.setFont(new java.awt.Font("Yu Gothic Medium", 2, 12)); // NOI18N
        cancelañadir.setText("Cancelar");
        cancelañadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelañadirMouseClicked(evt);
            }
        });
        cancelañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelañadirActionPerformed(evt);
            }
        });
        jPanel1.add(cancelañadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 90, 30));

        agregarusu.setFont(new java.awt.Font("Yu Gothic Medium", 2, 12)); // NOI18N
        agregarusu.setText("Agregar");
        jPanel1.add(agregarusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 90, 30));

        nameusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameusuActionPerformed(evt);
            }
        });
        jPanel1.add(nameusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 160, 30));

        passwusuario.setText("jPasswordField1");
        jPanel1.add(passwusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 140, 30));

        btnconusuario.setFont(new java.awt.Font("Yu Gothic Medium", 2, 12)); // NOI18N
        btnconusuario.setText("Consultar");
        btnconusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnconusuarioMouseClicked(evt);
            }
        });
        jPanel1.add(btnconusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 90, 30));

        btnmodusuario.setFont(new java.awt.Font("Yu Gothic Medium", 2, 12)); // NOI18N
        btnmodusuario.setText("Modificar");
        btnmodusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmodusuarioMouseClicked(evt);
            }
        });
        jPanel1.add(btnmodusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 90, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 2, 18)); // NOI18N
        jLabel5.setText("Id del Usuario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 130, -1));
        jPanel1.add(idusuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/12.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameusuActionPerformed

    private void cancelañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelañadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelañadirActionPerformed

    private void cancelañadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelañadirMouseClicked
    presentacion.Menu menu= new presentacion.Menu();
    menu.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cancelañadirMouseClicked

    private void btnmodusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodusuarioMouseClicked
presentacion.Mousuario mousuario= new presentacion.Mousuario();
    mousuario.setVisible(true);
    this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnmodusuarioMouseClicked

    private void btnconusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconusuarioMouseClicked
presentacion.Conusuario conusuario= new presentacion.Conusuario();
    conusuario.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnconusuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarusu;
    private javax.swing.JButton btnconusuario;
    private javax.swing.JButton btnmodusuario;
    private javax.swing.JButton cancelañadir;
    private javax.swing.JTextField idusuario1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameusu;
    private javax.swing.JPasswordField passwusuario;
    // End of variables declaration//GEN-END:variables
}
